### ISSUE TITLE
Google Drive integration not working

### ISSUE THREAD

**Issue by star4z** [star4z/planner.go#52]
On my phone Google Drive is not working and only displays error messages if I try to export. Otherwise, it seems to not react at all. I checked the Google API console and things seem to be in order, so it seems to be a client-side issue.

**Comment by star4z** [comment]
Here's the error from the logcat:

403 Forbidden
{
    "errors": [
        {
      "domain": "usageLimits",
      "reason": "dailyLimitExceededUnreg",
      "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
      "extendedHelp": "https://code.google.com/apis/console"
     }
   ],
   "code": 403,
   "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:919)

So maybe it's a server-side configuration issue? I'm looking into what I might need to change. Also, note the problem does not affect the app when run on the emulator, so perhaps it only affects the release version? Another theory would be that Google lets the emulator do whatever it wants in terms of API calls.

**Comment by star4z** [comment]
I confirmed that it works on the debug build on a physical device that the play version fails on.
